openapi: 3.0.0
info:
  version: 0.0-oas3
  title: Lunch Predictor
  description: >-
    predicts what kind of lunch a student has: free/reduced or standard using
    test scores. will either use 3 different defintions for scores (math,
    reading, writing) or use one defintion for all 3
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /scores/<math>/<read>/<write>:
    get: #possibly make it a post for multiple scores 
      tags:
        - scores
      operationId: lunch_predictor.get_scores
      description: 'returns math, reading, and writing scores'
      responses:
        '200':
          description: 'reading, writing, math scores'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scores'
        '405':
          description: 'not correct amount of scores'
  /prediction:
    get:
      tags:
        - prediction
      operationId: lunch_predictor.prediction
      description: returns the predicted lunch
      responses:
        '200':
          description: 'returns predicted lunch'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/prediction'
servers:
  - url: 'http://localhost:8080/carmhern'
components:
  schemas:
    scores:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    prediction:
      type: object
      required:
        - model
      properties:
        model:
          type: string
